java_test(
  name = "tests",
  srcs = glob(['*.java']),
  timeout = "short",
  deps = [
    "//src/main/java/org/servz/core",
    "//src/main/java/org/servz/handler",
    "//src/main/java/org/servz/handler:annotations",
    "//src/main/java/org/servz/http/component",
    "//src/main/java/org/servz/http/netty",
    "//src/main/java/org/servz/http:annotations",
    "//third_party/dagger",
    "//third_party/netty",
    "//third_party/testing",
  ],
)
