java_test(
  name = "tests",
  srcs = glob(['*.java']),
  timeout = "short",
  deps = [
    "//src/main/java/org/servz/http/netty",
    "//src/main/java/org/servz/http",
    "//third_party/dagger",
    "//third_party/testing",
  ],
)
