package(default_visibility = ["//visibility:public"])

java_library(
  name = "core",
  srcs = glob(['*.java']),
  deps = [
    "//src/main/java/org/servz/handler:annotations",
    "//src/main/java/org/servz/handler",
    "//src/main/java/org/servz/logging",
    "//third_party/dagger",
    "//third_party/guava",
    "//third_party/logging:logging-api",
  ]
)
