package(default_visibility = ["//visibility:public"])

java_library(
  name = "component",
  srcs = glob(['*.java']),
  deps = [
    "//src/main/java/org/servz/logging",
    "//src/main/java/org/servz/handler",
    "//src/main/java/org/servz/http:annotations",
    "//third_party/dagger",
    "//third_party/logging:logging-api",
    "//third_party/netty",
    "//third_party/guava",
    "//third_party/auto",
  ]
)
